#!/bin/sh

set -e

# Source debconf library
. /usr/share/debconf/confmodule
db_version 2.0
db_capb backup

if [ "$1" != "configure" ] && [ "$1" != "reconfigure" ]; then
	exit 0;
fi

if [ "$1" = "configure" ] && [ -f /usr/share/games/stratagus/war1gus/extracted ] && war1tool -V 1>/dev/null 2>&1; then

	HAS_VERSION="$(cat /usr/share/games/stratagus/war1gus/extracted 2>/dev/null)"
	NEW_VERSION="$(war1tool -V 2>/dev/null)"

	if [ "$HAS_VERSION" = "$NEW_VERSION" ]; then
		db_set war1gus/extractdata "false" || true
		db_stop || true
		exit 0
	fi

fi

db_reset war1gus/extractdata || true
db_fset war1gus/extractdata seen false || true
db_fset war1gus/cdpath seen false || true
db_fset war1gus/extractvideo seen false || true
db_fset war1gus/convertmusic seen false || true

while true; do

	db_beginblock || true
	db_input critical war1gus/extractdata || true
	db_endblock || true
	db_go || exit 10

	db_get war1gus/extractdata || true
	if [ "$RET" = "false" ]; then
		break
	fi

	db_beginblock || true
	db_input critical war1gus/cdpath || true
	db_input critical war1gus/extractvideo || true
	db_input critical war1gus/convertmusic || true
	db_endblock || true
	db_go || continue

	found="false"
	db_get war1gus/cdpath || true
	for CDPATH in "$RET" "$RET/data" "$RET/DATA"; do
		if [ -f "$CDPATH/data.war" ] || [ -f "$CDPATH/DATA.WAR" ] || [ -f "$CDPATH/DATA/data.war" ] || [ -f "$CDPATH/DATA/DATA.WAR" ] || [ -f "$CDPATH/FDATA/data.war" ] || [ -f "$CDPATH/FDATA/DATA.WAR" ]; then
			db_set war1gus/cdpath $CDPATH || true
			found="true"
			break
		fi
	done

	if [ "$found" = "true" ]; then
		break
	fi

	db_beginblock || true
	db_input critical war1gus/nodata || true
	db_endblock || true
	db_go || continue

done

db_stop || true
