#!/bin/sh

set -e

. /usr/share/debconf/confmodule

extract() {

	if [ $(dpkg-query -W -f='${Status}' musescore-soundfont-gm 2>/dev/null | grep -c "ok installed") -eq 1 ]; then
	    cp /usr/share/sounds/sf2/TimGM6mb.sf2 /usr/share/games/stratagus/wargus/music
	fi
	return $?

}

if [ "$1" = "configure" ]; then
	extract || exit $?
fi

#DEBHELPER#

exit 0
