name: macOS-arm64

on:
  workflow_dispatch:
  push:
    paths:
      - '**'
      - '!.github/**'
      - '!**.yml'
      - '.github/workflows/macos.yml'
      - '!**.md'
      - '!.vscode/**'
      - '!doc/**'

  pull_request:
    paths:
      - '**'
      - '!.github/**'
      - '!**.yml'
      - '.github/workflows/macos.yml'
      - '!**.md'
      - '!.vscode/**'
      - '!doc/**'

jobs:
  macos:
    runs-on: macos-latest

    steps:
    - name: Checkout War1gus
      uses: actions/checkout@v4
      with:
        repository: Wargus/war1gus
        submodules: recursive
        path: war1gus
    
    - name: Checkout Stratagus
      uses: actions/checkout@v4
      with: 
        repository: Wargus/stratagus
        submodules: recursive
        path: stratagus

    - name: Install dependencies
      run: brew install dylibbundler sdl2 sdl2_mixer sdl2_image lua ffmpeg

    - name: cmake --version
      run: cmake --version

    - name: Build Stratagus
      run: |
        cmake stratagus -B stratagus/build \
        -DCMAKE_BUILD_TYPE=Release \
        -DBUILD_VENDORED_LUA=ON \
        -DBUILD_VENDORED_SDL=OFF \
        -DBUILD_VENDORED_MEDIA_LIBS=OFF \
        -DBUILD_TESTING=1
        cmake --build stratagus/build --config Release
    
    - name: Build War1gus
      run: |
        cmake war1gus -B war1gus/build \
        -DSTRATAGUS_INCLUDE_DIR=../stratagus/gameheaders \
        -DSTRATAGUS=../stratagus/build/stratagus \
        -DENABLE_VENDORED_LIBS=OFF
        cmake --build war1gus/build --config Release

    - name: Create War1gus app bundle
      run: |
        export STRATAGUS_INCLUDE_DIR=stratagus/gameheaders
        export STRATAGUS=stratagus/build/stratagus
        war1gus/mac/bundle.sh
        
        dylibbundler -of -cd -b -x war1gus/mac/War1gus.app/Contents/MacOS/stratagus -d war1gus/mac/War1gus.app/Contents/libs/
        dylibbundler -of -cd -b -x war1gus/mac/War1gus.app/Contents/MacOS/war1tool -d war1gus/mac/War1gus.app/Contents/libs/
        
        codesign --force --deep --sign - war1gus/mac/War1gus.app
        
    - name: Create dmg
      run: hdiutil create -volname "War1gus" -srcfolder "war1gus/mac/War1gus.app" "War1gus-arm64"
    
    - name: Upload artifacts - macOS arm64
      uses: actions/upload-artifact@v4
      with:
        name: War1gus-macOS-arm64
        path: War1gus-arm64.dmg
        if-no-files-found: error